from time import sleep

main_opts = [
        "Add Kali repositories & Update",
        "View Categories",
        "Install classicmenu indicator",
        "Install Kali menu",
        "Help"
]

sub_opts = [
        "Add kali linux repositories",
        "Update",
        "Remove all kali linux repositories",
        "View sources.list file contents",
        "Edit the sources.list file"
]

categories = [
        "Information Gathering",
        "Vulnerability Analysis",
        "Wireless Attacks",
        "Web Applications",
        "Sniffing & Spoofing",
        "Maintaining Access",
        "Reporting Tools",
        "Exploitation Tools",
        "Forensics Tools",
        "Stress Testing",
        "Password Attacks",
        "Reverse Engineering",
        "Hardware Hacking",
        "Extra"
]

tool_command = {
    "Information Gathering": {
        "acccheck": "apt-get install acccheck",
        "ace-voip": "apt-get install ace-voip",
        "Amap": "apt-get install amap",
        "Automater": "apt-get install automater",
        "bing-ip2hosts": "wget http://www.morningstarsecurity.com/downloads/bing-ip2hosts-0.4.tar.gz && tar -xzvf bing-ip2hosts-0.4.tar.gz && cp bing-ip2hosts-0.4/bing-ip2hosts /usr/local/bin/",
        "braa": "apt-get install braa",
        "CaseFile": "apt-get install casefile",
        "CDPSnarf": "apt-get install cdpsnarf",
        "cisco-torch": "apt-get install cisco-torch",
        "Cookie Cadger": "apt-get install cookie-cadger",
        "copy-router-config": "apt-get install copy-router-config",
        "DMitry": "apt-get install dmitry",
        "dnmap": "apt-get install dnmap",
        "dnsenum": "apt-get install dnsenum",
        "dnsmap": "apt-get install dnsmap",
        "DNSRecon": "apt-get install dnsrecon",
        "dnstracer": "apt-get install dnstracer",
        "dnswalk": "apt-get install dnswalk",
        "DotDotPwn": "apt-get install dotdotpwn",
        "enum4linux": "apt-get install enum4linux",
        "enumIAX": "apt-get install enumiax",
        "exploitdb": "apt-get install exploitdb",
        "Fierce": "apt-get install fierce",
        "Firewalk": "apt-get install firewalk",
        "fragroute": "apt-get install fragrouter",
        "fragrouter": "apt-get install fragrouter",
        "Ghost Phisher": "apt-get install ghost-phisher",
        "GoLismero": "apt-get install golismero",
        "lbd": "apt-get install lbd",
        "Maltego Teeth": "apt-get install maltego-teeth",
        "masscan": "apt-get install masscan",
        "Metagoofil": "apt-get install metagoofil",
        "Miranda": "apt-get install miranda",
        "Nmap": "apt-get install nmap",
        "ntop": None,
        "p0f": "apt-get install p0f",
        "Parsero": "apt-get install parsero",
        "Recon-ng": "apt-get install recon-ng",
        "SET": "apt-get install set",
        "smtp-user-enum": "apt-get install smtp-user-enum",
        "snmpcheck": "apt-get install snmpcheck",
        "sslcaudit": "apt-get install sslcaudit",
        "SSLsplit": "apt-get install sslsplit",
        "sslstrip": "apt-get install sslstrip",
        "SSLyze": "apt-get install sslyze",
        "THC-IPV6": "apt-get install thc-ipv6",
        "theHarvester": "apt-get install theharvester",
        "TLSSLed": "apt-get install tlssled",
        "twofi": "apt-get install twofi",
        "URLCrazy": "apt-get install urlcrazy",
        "Wireshark": "apt-get install wireshark",
        "WOL-E": "apt-get install wol-e",
        "Xplico": "apt-get install xplico",
        "iSMTP": "apt-get install ismtp",
        "InTrace": "apt-get install intrace",
        "hping3": "apt-get install hping3",
        "goofile": "apt-get install goofile"
    },
    "Vulnerability Analysis": {
        "BBQSQL": "apt-get install bbqsql",
        "BED": "apt-get install bed",
        "cisco-auditing-tool": "apt-get install cisco-auditing-tool",
        "cisco-global-exploiter": "apt-get install cisco-global-exploiter",
        "cisco-ocs": "apt-get install cisco-ocs",
        "cisco-torch": "apt-get install cisco-torch",
        "copy-router-config": "apt-get install copy-router-config",
        "commix": "apt-get install git && git clone https://github.com/stasinopoulos/commix.git commix && cd commix && python ./commix.py --install",
        "DBPwAudit": "apt-get install git && git clone git://git.kali.org/packages/dbpwaudit.git",
        "DoonaDot": "apt-get install doona",
        "DotPwn": "apt-get install dotdotpwn",
        "Greenbone Security Assistant": "apt-get install greenbone-security-assistant",
        "GSD": "apt-get install git && git clone git://git.kali.org/packages/gsd.git",
        "HexorBase": "apt-get install hexorbase",
        "Inguma": "echo '\nPlease download inguma from : http://inguma.sourceforge.net' ",
        "jSQL": "apt-get install jsql",
        "Lynis": "apt-get install lynis",
        "Nmap": "apt-get install nmap",
        "ohrwurm": "apt-get install ohrwurm",
        "openvas-administrator": "apt-get install openvas-administrator",
        "openvas-cli": "apt-get install openvas-cli",
        "openvas-manager": "apt-get install openvas-manager",
        "openvas-scanner": "apt-get install openvas-scanner",
        "Oscanner": "apt-get install oscanner",
        "Powerfuzzer": "apt-get install powerfuzzer",
        "sfuzz": "apt-get install sfuzz",
        "SidGuesser": "apt-get install sidguesser",
        "SIPArmyKnife": "apt-get install siparmyknife",
        "sqlmap": "apt-get install sqlmap",
        "Sqlninja": "apt-get install sqlninja",
        "sqlsus": "apt-get install sqlsus",
        "THC-IPV6": "apt-get install thc-ipv6",
        "tnscmd10g": "apt-get install tnscmd10g",
        "unix-privesc-check": "apt-get install unix-privesc-check",
        "Yersinia": "apt-get install yersinia"
    },
    "Wireless Attacks": {
        "Aircrack-ng": "apt-get install aircrack-ng",
        "Asleap": "apt-get install asleap",
        "Bluelog": "apt-get install bluelog",
        "BlueMaho": "apt-get install git && git clone git://git.kali.org/packages/bluemaho.git",
        "Bluepot": "apt-get install git && git clone git://git.kali.org/packages/bluepot.git",
        "BlueRanger": "apt-get install blueranger",
        "Bluesnarfer": "apt-get install bluesnarfer",
        "Bully": "apt-get install bully",
        "coWPAtty": "apt-get install cowpatty",
        "crackle": "apt-get install crackle",
        "eapmd5pass": "apt-get install eapmd5pass",
        "Fern Wifi Cracker": "apt-get install fern-wifi-cracker",
        "Ghost Phisher": "apt-get install ghost-phisher",
        "GISKismet": "apt-get install giskismet",
        "kalibrate-rtl": "apt-get install kalibrate-rtl",
        "KillerBee": "apt-get install killerbee",
        "Kismet": "apt-get install kismet",
        "mdk3": "apt-get install mdk3",
        "mfcuk": "apt-get install mfcuk",
        "mfoc": "apt-get install mfoc",
        "mfterm": "apt-get install mfterm",
        "Multimon-NG": "apt-get install multimon-ng",
        "PixieWPS": "apt-get install pixiewps",
        "Reaver": "apt-get install reaver",
        "redfang": "apt-get install redfang",
        "RTLSDR Scanner": "apt-get install rtlsdr-scanner",
        "Spooftooph": "apt-get install spooftooph",
        "Wifite": "apt-get install wifite",
        "gr-scan": "apt-get install git && git clone git://git.kali.org/packages/gr-scan.git"
    },
    "Web Applications": {
        "apache-users": "apt-get install apache-users",
        "Arachni": "apt-get install arachni",
        "BBQSQL": "apt-get install bbqsql",
        "BlindElephant": "apt-get install blindelephant",
        "Burp Suite": "apt-get install burpsuite",
        "commix": "apt-get install git && git clone https://github.com/stasinopoulos/commix.git commix && cd commix && python ./commix.py --install",
        "CutyCapt": "apt-get install cutycapt",
        "DAVTest": "apt-get install davtest",
        "deblaze": "apt-get install deblaze",
        "DIRB": "apt-get install dirbuster",
        "DirBuster": "apt-get install dirbuster",
        "fimap": "apt-get install fimap",
        "FunkLoad": "apt-get install funkload",
        "Grabber": "apt-get install grabber",
        "jboss-autopwn": "apt-get install jboss-autopwn",
        "joomscan": "apt-get install joomscan",
        "jSQL": "apt-get install jsql",
        "Maltego Teeth": "apt-get install maltego-teeth",
        "PadBuster": "apt-get install padbuster",
        "Paros": "apt-get install paros",
        "Parsero": "apt-get install parsero",
        "plecost": "apt-get install plecost",
        "Powerfuzzer": "apt-get install powerfuzzer",
        "ProxyStrike": "apt-get install proxystrike",
        "Recon-ng": "apt-get install recon-ng",
        "Skipfish": "apt-get install skipfish",
        "sqlmap": "apt-get install sqlmap",
        "Sqlninja": "apt-get install sqlninja",
        "sqlsus": "apt-get install sqlsus",
        "ua-tester": "apt-get install ua-tester",
        "Uniscan": "apt-get install uniscan",
        "Vega": "apt-get install vega",
        "w3af": "apt-get install w3af",
        "WebScarab": "apt-get install webscarab",
        "Webshag": None,
        "WebSlayer": "apt-get install git && git clone git://git.kali.org/packages/webslayer.git",
        "WebSploit": "apt-get install websploit",
        "Wfuzz": "apt-get install wfuzz",
        "WPScan": "apt-get install wpscan",
        "XSSer": "apt-get install xsser",
        "zaproxy": "apt-get install zaproxy"
    },
    "Sniffing & Spoofing": {
        "Burp Suite": "apt-get install burpsuite",
        "DNSChef": "apt-get install dnschef",
        "fiked": "apt-get install fiked",
        "hamster-sidejack": "apt-get install hamster-sidejack",
        "HexInject": "apt-get install hexinject",
        "iaxflood": "apt-get install iaxflood",
        "inviteflood": "apt-get install inviteflood",
        "iSMTP": "apt-get install ismtp",
        "isr-evilgrade": "apt-get install git && git clone git://git.kali.org/packages/isr-evilgrade.git",
        "mitmproxy": "apt-get install mitmproxy",
        "ohrwurm": "apt-get install ohrwurm",
        "protos-sip": "apt-get install protos-sip",
        "rebind": "apt-get install rebind",
        "responder": "apt-get install responder",
        "rtpbreak": "apt-get install rtpbreak",
        "rtpmixsound": "apt-get install rtpmixsound",
        "sctpscan": "apt-get install sctpscan",
        "SIPArmyKnife": "apt-get install siparmyknife",
        "SIPp": "apt-get install sipp",
        "SIPVicious": "apt-get install sipvicious",
        "SniffJoke": "apt-get install sniffjoke",
        "SSLsplit": "apt-get install sslsplit",
        "sslstrip": "apt-get install sslstrip",
        "THC-IPV6": "apt-get install thc-ipv6",
        "VoIPHopper": "apt-get install voiphopper",
        "WebScarab": "apt-get install webscarab",
        "Wifi Honey": "apt-get install wifi-honey",
        "Wireshark": "apt-get install wireshark",
        "xspy": "apt-get install xspy",
        "Yersinia": "apt-get install yersinia",
        "zaproxy": "apt-get install zaproxy",
        "rtpinsertsound": "apt-get install rtpinsertsound"
    },
    "Maintaining Access": {
        "CryptCat": "apt-get install cryptcat",
        "Cymothoa": "apt-get install cymothoa",
        "dbd": "apt-get install dbd",
        "dns2tcp": "apt-get install dns2tcp",
        "http-tunnel": "apt-get install http-tunnel",
        "HTTPTunnel": "apt-get install httptunnel",
        "Intersect": "apt-get install intersect",
        "Nishang": "apt-get install nishang",
        "polenum": "apt-get install polenum",
        "PowerSploit": "apt-get install powersploit",
        "pwnat": "apt-get install pwnat",
        "RidEnum": "apt-get install ridenum",
        "sbd": "apt-get install sbd",
        "U3-Pwn": "apt-get install u3-pwn",
        "Webshells": "apt-get install webshells",
        "Weevely": "apt-get install weevely"
    },
    "Reporting Tools": {
        "CaseFile": "apt-get install casefile",
        "CutyCapt": "apt-get install cutycapt",
        "dos2unix": "apt-get install dos2unix",
        "Dradis": "apt-get install dradis",
        "KeepNote": "apt-get install keepnote",
        "MagicTree": "apt-get install magictree",
        "Metagoofil": "apt-get install metagoofil",
        "Nipper-ng": "apt-get install nipper-ng",
        "pipal": "apt-get install pipal"
    },
    "Exploitation Tools": {
        "Armitage": "apt-get install armitage",
        "Backdoor Factory": "apt-get install backdoor-factory",
        "BeEF": "apt-get install beef-xss",
        "cisco-auditing-tool": "apt-get install cisco-auditing-tool",
        "cisco-global-exploiter": "apt-get install cisco-global-exploiter",
        "cisco-ocs": "apt-get install cisco-ocs",
        "cisco-torch": "apt-get install cisco-torch",
        "commix": "apt-get install git && git clone https://github.com/stasinopoulos/commix.git commix && cd commix && python ./commix.py --install",
        "crackle": "apt-get install crackle",
        "jboss-autopwn": "apt-get install jboss-autopwn",
        "Linux Exploit Suggester": "apt-get install linux-exploit-suggester",
        "Maltego Teeth": "apt-get install maltego-teeth",
        "SET": "apt-get install set",
        "ShellNoob": "apt-get install shellnoob",
        "sqlmap": "apt-get install sqlmap",
        "THC-IPV6": "apt-get install thc-ipv6",
        "Yersinia": "apt-get install yersinia"
    },
    "Forensics Tools": {
        "Binwalk": "apt-get install binwalk",
        "bulk-extractor": "apt-get install bulk-extractor",
        "Capstone": "apt-get install git && git clone git://git.kali.org/packages/capstone.git",
        "chntpw": "apt-get install chntpw",
        "Cuckoo": "apt-get install cuckoo",
        "dc3dd": "apt-get install dc3dd",
        "ddrescue": "apt-get install ddrescue",
        "DFF": None,
        "diStorm3": "apt-get install python-diStorm3",
        "Dumpzilla": "apt-get install dumpzilla",
        "RegRipper": None,
        "Volatility": "apt-get install volatility",
        "extundelete": "apt-get install extundelete",
        "Foremost": "apt-get install foremost",
        "Galleta": "apt-get install galleta",
        "Guymager": "apt-get install guymager",
        "iPhone Backup Analyzer": "apt-get install iphone-backup-analyzer",
        "p0f": "apt-get install p0f",
        "pdf-parser": "apt-get install pdf-parser",
        "pdfid": "apt-get install pdfid",
        "pdgmail": "apt-get install pdgmail",
        "peepdf": "apt-get install peepdf",
        "Xplico": "apt-get install xplico"
    },
    "Stress Testing": {
        "DHCPig": "apt-get install dhcpig",
        "FunkLoad": "apt-get install funkload",
        "iaxflood": "apt-get install iaxflood",
        "Inundator": "apt-get install git && git clone git://git.kali.org/packages/inundator.git",
        "inviteflood": "apt-get install inviteflood",
        "ipv6-toolkit": "apt-get install ipv6-toolkit",
        "mdk3": "apt-get install mdk3",
        "Reaver": "apt-get install reaver",
        "rtpflood": "apt-get install rtpflood",
        "SlowHTTPTest": "apt-get install slowhttptest",
        "t50": "apt-get install t50",
        "Termineter": "apt-get install termineter",
        "THC-IPV6": "apt-get install thc-ipv6",
        "THC-SSL-DOS": "apt-get install thc-ssl-dos "
    },
    "Password Attacks": {
        "acccheck": "apt-get install acccheck",
        "Burp Suite": "apt-get install burpsuite",
        "CeWL": "apt-get install cewl",
        "chntpw": "apt-get install chntpw",
        "cisco-auditing-tool": "apt-get install cisco-auditing-tool",
        "CmosPwd": "apt-get install cmospwd",
        "creddump": "apt-get install creddump",
        "crunch": "apt-get install crunch",
        "DBPwAudit": "apt-get install git && git clone git://git.kali.org/packages/dbpwaudit.git",
        "findmyhash": "apt-get install findmyhash",
        "gpp-decrypt": "apt-get install gpp-decrypt",
        "hash-identifier": "apt-get install hash-identifier",
        "HexorBase": "apt-get install hexorbase",
        "THC-Hydra": "echo 'please visit : https://www.thc.org/thc-hydra/' ",
        "John the Ripper": "apt-get install john",
        "Johnny": "apt-get install johnny",
        "keimpx": "apt-get install keimpx",
        "Maskprocessor": "apt-get install maskprocessor",
        "multiforcer": "apt-get install multiforcer",
        "Ncrack": "apt-get install ncrack",
        "oclgausscrack": "apt-get install oclgausscrack",
        "PACK": "apt-get install pack",
        "patator": "apt-get install patator",
        "phrasendrescher": "echo 'please visit : http://www.leidecker.info/projects/phrasendrescher/index.shtml' ",
        "polenum": "apt-get install polenum",
        "RainbowCrack": "apt-get install rainbowcrack",
        "rcracki-mt": "apt-get install rcracki-mt",
        "RSMangler": "apt-get install rsmangler",
        "SQLdict": None,
        "Statsprocessor": "apt-get install statsprocessor",
        "THC-pptp-bruter": "apt-get install thc-pptp-bruter",
        "TrueCrack": "apt-get install truecrack",
        "WebScarab": "apt-get install webscarab",
        "wordlists": "apt-get install wordlists",
        "zaproxy": "apt-get install zaproxy",
        "Maltego Teeth": "apt-get install maltego-teeth"
    },
    "Reverse Engineering": {
        "apktool": "apt-get install apktool",
        "dex2jar": "apt-get install dex2jar",
        "diStorm3": "apt-get install python-diStorm3",
        "edb-debugger": "apt-get install edb-debugger",
        "jad": "apt-get install jad",
        "javasnoop": "apt-get install javasnoop",
        "JD-GUI": "apt-get install JD",
        "OllyDbg": "apt-get install OllyDbg",
        "smali": "apt-get install smali",
        "Valgrind": "apt-get install Valgrind",
        "YARA": "apt-get install YARA"
    },
    "Hardware Hacking": {
        "android-sdk": "apt-get install android-sdk",
        "apktool": "apt-get install apktool",
        "Arduino": "apt-get install arduino",
        "dex2jar": "apt-get install dex2jar",
        "Sakis3G": "apt-get install sakis3g",
        "smali": "apt-get install smali"
    },
    "Extra": {
        "Wifresti": "apt-get install git && git clone https://github.com/LionSec/wifresti.git && cp wifresti/wifresti.py /usr/bin/wifresti && chmod +x /usr/bin/wifresti && wifresti",
        "Squid3": "apt-get install squid3"
    }
}

all_tools = [tool for cat in tool_command.keys() for tool in tool_command.get(cat).keys() if tool_command[cat][tool]]
tools_count = len(all_tools)

banner = f"""

 $$\   $$\             $$\                         $$\ $$\           
 $$ | $$  |            $$ |                        $$ |\__|          
 $$ |$$  /  $$$$$$\  $$$$$$\    $$$$$$\   $$$$$$\  $$ |$$\ $$$$$$$\  
 $$$$$  /   \____$$\ \_$$  _|  $$  __$$\ $$  __$$\ $$ |$$ |$$  __$$\ 
 $$  $$<    $$$$$$$ |  \033[1;36mKali linux tools installer\033[1;m |$$ |$$ |$$ |  $$ |
 \033[1;36m$$ |\$$\  $$  __$$ |  $$ |$$\ $$ |  $$ |$$ |  $$ |$$ |$$ |$$ |  $$ |
 $$ | \$$\ \$$$$$$$ |  \$$$$  |\$$$$$$  |\$$$$$$  |$$ |$$ |$$ |  $$ |
 \__|  \__| \_______|   \____/  \______/  \______/ \__|\__|\__|  \__| 4.0v \033[1;m


 \033[1;32m+ -- -- +=[ Author: LionSec | Unicorn Code Inc (teddbug-S) ]>>\033[1;m
 \033[1;32m+ -- -- +=[ {tools_count} tools available!  ]>>\033[1;m


\033[1;91m[W] Before updating your system, please remove all Kali-linux repositories to avoid any kind of problem.\033[1;m

"""